
package com.soap.wsdl;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CollectionWS", targetNamespace = "http://album.soap.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CollectionWS {


    /**
     * 
     * @param product
     * @param year
     * @param name
     * @return
     *     returns com.soap.wsdl.Album
     */
    @WebMethod
    @WebResult(name = "album", targetNamespace = "")
    @RequestWrapper(localName = "insertAlbum", targetNamespace = "http://album.soap.com/", className = "com.soap.wsdl.InsertAlbum")
    @ResponseWrapper(localName = "insertAlbumResponse", targetNamespace = "http://album.soap.com/", className = "com.soap.wsdl.InsertAlbumResponse")
    @Action(input = "http://album.soap.com/CollectionWS/insertAlbumRequest", output = "http://album.soap.com/CollectionWS/insertAlbumResponse")
    public Album insertAlbum(
        @WebParam(name = "name", targetNamespace = "")
        String name,
        @WebParam(name = "year", targetNamespace = "")
        int year,
        @WebParam(name = "product", targetNamespace = "")
        String product);

    /**
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(name = "albumTitle", targetNamespace = "")
    @RequestWrapper(localName = "getAlbumsTitle", targetNamespace = "http://album.soap.com/", className = "com.soap.wsdl.GetAlbumsTitle")
    @ResponseWrapper(localName = "getAlbumsTitleResponse", targetNamespace = "http://album.soap.com/", className = "com.soap.wsdl.GetAlbumsTitleResponse")
    @Action(input = "http://album.soap.com/CollectionWS/getAlbumsTitleRequest", output = "http://album.soap.com/CollectionWS/getAlbumsTitleResponse")
    public List<String> getAlbumsTitle();

    /**
     * 
     * @return
     *     returns java.util.List<com.soap.wsdl.Album>
     */
    @WebMethod
    @WebResult(name = "album", targetNamespace = "")
    @RequestWrapper(localName = "getAlbums", targetNamespace = "http://album.soap.com/", className = "com.soap.wsdl.GetAlbums")
    @ResponseWrapper(localName = "getAlbumsResponse", targetNamespace = "http://album.soap.com/", className = "com.soap.wsdl.GetAlbumsResponse")
    @Action(input = "http://album.soap.com/CollectionWS/getAlbumsRequest", output = "http://album.soap.com/CollectionWS/getAlbumsResponse")
    public List<Album> getAlbums();

    /**
     * 
     * @param year
     * @return
     *     returns java.util.List<com.soap.wsdl.Album>
     */
    @WebMethod
    @WebResult(name = "album", targetNamespace = "")
    @RequestWrapper(localName = "getAlbumByYear", targetNamespace = "http://album.soap.com/", className = "com.soap.wsdl.GetAlbumByYear")
    @ResponseWrapper(localName = "getAlbumByYearResponse", targetNamespace = "http://album.soap.com/", className = "com.soap.wsdl.GetAlbumByYearResponse")
    @Action(input = "http://album.soap.com/CollectionWS/getAlbumByYearRequest", output = "http://album.soap.com/CollectionWS/getAlbumByYearResponse")
    public List<Album> getAlbumByYear(
        @WebParam(name = "year", targetNamespace = "")
        int year);

}
